export interface Product {
  id: number;
  name: string;
  model: string;
  category: string;
  subCategory: string;
  resolution: string;
  interface: string;
  shutter: string;
  fps: string;
  price: string;
  priceNum: number;
  badge?: string;
  badgeColor?: string;
  rating: number;
  reviews: number;
  image?: string;
  images?: string[];
  description: string;
  features: string[];
  specs: Record<string, string>;
  inStock: boolean;
  detailUrl?: string;
}

// New 7 categories for Utocom products
export const categories = [
  { id: "3d-microscope", name: "3D Microscopes", count: 6 },
  { id: "metallographic-microscope", name: "Metallographic Microscopes", count: 3 },
  { id: "measuring-microscope", name: "Measuring Microscopes", count: 3 },
  { id: "electronic-microscope", name: "Electronic Microscopes", count: 4 },
  { id: "vision-inspection", name: "Vision Inspection", count: 4 },
  { id: "thermal-camera", name: "Thermal Cameras", count: 2 },
  { id: "specialized-microscope", name: "Specialized Microscopes", count: 2 },
];

// 24 New Products from troysupply_products_detailed.xlsx
export const products: Product[] = [
  // ========== 3D Microscopes (6 products) ==========
  {
    id: 1,
    name: "3D View Electric Microscope",
    model: "TVN-2K30/4K30-EP3D_B",
    category: "3d-microscope",
    subCategory: "3D Digital Microscope",
    resolution: "2K/4K",
    interface: "HDMI",
    shutter: "Rolling Shutter",
    fps: "30fps",
    price: "Contact Us",
    priceNum: 0,
    badge: "New",
    badgeColor: "bg-green-500",
    rating: 4.8,
    reviews: 128,
    image: "/images/products/tvn-2k30-4k30-ep3d-b/main.jpg",
    images: [
      "/images/products/tvn-2k30-4k30-ep3d-b/main.jpg",
      "/images/products/tvn-2k30-4k30-ep3d-b/detail1.jpg",
      "/images/products/tvn-2k30-4k30-ep3d-b/detail2.jpg",
    ],
    description: "The TVN-2K30/4K30 high-definition industrial camera features a built-in personalized interface editing function, template application, mouse operation, USB flash drive storage, and includes functions such as automatic edge finding, automatic contouring, horizontal and vertical flipping, line/circle calibration, data export, and playback browsing.",
    features: [
      "2K/4K High Resolution",
      "Personalized interface editing",
      "Template application",
      "Automatic edge finding",
      "Automatic contouring",
      "Line/circle calibration",
      "Data export functionality",
      "Multiple measurement tools",
    ],
    specs: {
      "Model": "TVN-2K30/4K30-EP3D_B",
      "Resolution": "2K/4K",
      "Frame Rate": "30fps",
      "Interface": "HDMI, USB",
      "Storage": "USB flash drive",
      "Control": "Mouse operation",
      "Functions": "Edge finding, contouring, calibration",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/troy-3d-view-of-electric-microscope-model-tvn-2k30-4k30-ep3d-b_p519.html",
  },
  {
    id: 2,
    name: "3D View Type Electric Microscope",
    model: "TVN-8008_A",
    category: "3d-microscope",
    subCategory: "3D Digital Microscope",
    resolution: "1920 x 1080",
    interface: "HDMI",
    shutter: "Rolling Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.7,
    reviews: 96,
    image: "/images/products/tvn-8008-a/main.jpg",
    images: [
      "/images/products/tvn-8008-a/main.jpg",
      "/images/products/tvn-8008-a/detail1.jpg",
    ],
    description: "Multi-function digital microscope with 3D viewing capability. Features HDMI output, dual USB ports, and C-Mount lens interface for versatile industrial inspection.",
    features: [
      "1920x1080 Full HD Resolution",
      "3D viewing capability",
      "C-Mount lens interface",
      "Dual USB ports",
      "U-disk storage",
      "Multi-function design",
    ],
    specs: {
      "Model": "TVN-8008_A",
      "Resolution": "1920 x 1080",
      "Video Port": "HDMI",
      "Color": "Color",
      "Sensor Size": "1/3\"",
      "USB Port": "2 Port",
      "Storage": "U-disk",
      "Lens Interface": "C-Mount",
      "Power": "DC 12V",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/troy-3d-view-type-of-electric-microscope-model-tvn-8008-a_p469.html",
  },
  {
    id: 3,
    name: "3D Digital Microscope",
    model: "TVN-360A",
    category: "3d-microscope",
    subCategory: "3D Digital Microscope",
    resolution: "HD",
    interface: "USB",
    shutter: "Rolling Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    badge: "Hot",
    badgeColor: "bg-red-500",
    rating: 4.9,
    reviews: 215,
    image: "/images/products/tvn-360a/main.jpg",
    images: [
      "/images/products/tvn-360a/main.jpg",
      "/images/products/tvn-360a/detail1.jpg",
    ],
    description: "3D Digital Microscope with three-dimensional viewing. Features 0.7-4.5X optical magnification, frame freeze, image comparison, strong light suppression, and edge enhancement.",
    features: [
      "3D viewing with plane switch",
      "0.7-4.5X optical magnification",
      "60fps high speed",
      "Frame freeze & image comparison",
      "Strong light suppression",
      "Edge enhancement",
      "Color independent adjustment",
      "Auto white balance & exposure",
    ],
    specs: {
      "Model": "TVN-360A",
      "Optical Magnification": "0.7-4.5X",
      "Frame Rate": "60fps",
      "Control": "Mouse operation",
      "Storage": "U disk",
      "Features": "Frame freeze, image comparison",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/china-top-of-3d-digital-microscope-tvn-360a_p405.html",
  },
  {
    id: 4,
    name: "3D Depth Digital Microscope",
    model: "TVN-3D9000",
    category: "3d-microscope",
    subCategory: "3D Depth Microscope",
    resolution: "HD",
    interface: "HDMI",
    shutter: "Rolling Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    badge: "New",
    badgeColor: "bg-green-500",
    rating: 4.8,
    reviews: 87,
    image: "/images/products/tvn-3d9000/main.jpg",
    images: [
      "/images/products/tvn-3d9000/main.jpg",
      "/images/products/tvn-3d9000/detail1.jpg",
    ],
    description: "TVN-3D9000 with 3D deep view measuring features. High-quality optical system with HD lens, multiple objective selection, stereoscopic 3D imaging, and high-precision measurement.",
    features: [
      "High-quality optical system",
      "HD lens",
      "Multiple objective selection",
      "Stereoscopic 3D imaging",
      "High-precision measurement",
      "Quality assurance",
    ],
    specs: {
      "Model": "TVN-3D9000",
      "Optical System": "High-quality",
      "Lens": "HD",
      "Objectives": "Multiple selection",
      "Imaging": "Stereoscopic 3D",
      "Measurement": "High-precision",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/china-top-3d-depth-digital-microscope-tvn-3d9000_p397.html",
  },
  {
    id: 5,
    name: "3D Digital Microscope System",
    model: "TVN-800+P3D",
    category: "3d-microscope",
    subCategory: "3D Digital Microscope",
    resolution: "HD",
    interface: "HDMI",
    shutter: "Rolling Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.7,
    reviews: 64,
    image: "/images/products/tvn-800-p3d/main.jpg",
    images: [
      "/images/products/tvn-800-p3d/main.jpg",
      "/images/products/tvn-800-p3d/detail1.jpg",
    ],
    description: "Complete 3D Digital Microscope system including 13-inch screen, lens, LED light, processing unit, and all necessary accessories.",
    features: [
      "Complete 3D microscope system",
      "13 inch screen included",
      "Lens, LED light, processing unit",
      "Complete accessories",
      "Ready to use",
    ],
    specs: {
      "Model": "TVN-800+P3D",
      "Screen": "13 inch",
      "Components": "Lens, LED light, processing unit",
      "Accessories": "DC power cable, mouse, HDMI cable",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/china-best-of-3d-digital-microscope-tvn-800-p3d_p396.html",
  },
  {
    id: 6,
    name: "Manual 3D Microscope",
    model: "TVN-800_3D",
    category: "3d-microscope",
    subCategory: "3D Manual Microscope",
    resolution: "HD",
    interface: "USB",
    shutter: "Rolling Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    badge: "Hot",
    badgeColor: "bg-red-500",
    rating: 4.8,
    reviews: 142,
    image: "/images/products/tvn-800-3d/main.jpg",
    images: [
      "/images/products/tvn-800-3d/main.jpg",
      "/images/products/tvn-800-3d/detail1.jpg",
    ],
    description: "Microscope 3D View with LED ring light source, automatic edge finding, automatic circle finding, picture and data save/export, zoom without blur.",
    features: [
      "LED ring light source",
      "Dynamic adjustment",
      "Automatic edge finding",
      "Automatic circle finding",
      "Picture save and export",
      "Data save and export",
      "Zoom without blur",
    ],
    specs: {
      "Model": "TVN-800_3D",
      "Light Source": "LED ring light",
      "Functions": "Auto edge/circle finding",
      "Storage": "Picture and data save/export",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/hot-sale-of-manual-3d-microscope-tvn-800-3d_p254.html",
  },

  // ========== Metallographic Microscopes (3 products) ==========
  {
    id: 7,
    name: "Metallographic Tool Microscope",
    model: "TVN-50MINI",
    category: "metallographic-microscope",
    subCategory: "Metallographic Microscope",
    resolution: "High-definition",
    interface: "USB",
    shutter: "Rolling Shutter",
    fps: "30fps",
    price: "Contact Us",
    priceNum: 0,
    badge: "New",
    badgeColor: "bg-green-500",
    rating: 4.9,
    reviews: 78,
    image: "/images/products/tvn-50mini/main.jpg",
    images: [
      "/images/products/tvn-50mini/main.jpg",
      "/images/products/tvn-50mini/detail1.jpg",
    ],
    description: "Desktop Metallographic Measuring Microscope combining high magnification with X, Y, and Z dimensional measurement capabilities. Multifunctional measuring instrument with high-precision linear measurement and observation.",
    features: [
      "High magnification metallographic observation",
      "X, Y, Z dimensional measurement",
      "High-precision linear measurement",
      "Multifunctional design",
      "Desktop form factor",
    ],
    specs: {
      "Model": "TVN-50MINI",
      "Resolution": "High-definition",
      "Measurement": "X, Y, Z dimensional",
      "Function": "High-precision linear measurement",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/china-best-of-metallographic-tool-microscope-tvn-50mini_p527.html",
  },
  {
    id: 8,
    name: "Digital Metallographic Microscope",
    model: "TVN-MT4K80",
    category: "metallographic-microscope",
    subCategory: "Digital Metallographic Microscope",
    resolution: "4K",
    interface: "HDMI",
    shutter: "Rolling Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    badge: "4K",
    badgeColor: "bg-blue-500",
    rating: 4.8,
    reviews: 156,
    image: "/images/products/tvn-mt4k80/main.jpg",
    images: [
      "/images/products/tvn-mt4k80/main.jpg",
      "/images/products/tvn-mt4k80/detail1.jpg",
    ],
    description: "Digital metallographic microscope for high-end manufacturing and research. Features 4K resolution, high-power LED lighting with reflection and transmission, bright field, dark field, DIC, and polarized light observations.",
    features: [
      "4K Ultra HD Resolution",
      "High-power LED lighting",
      "Reflection and transmission lighting",
      "Bright field observation",
      "Dark field observation",
      "DIC differential interference",
      "Polarized light observation",
      "Ergonomic design",
    ],
    specs: {
      "Model": "TVN-MT4K80",
      "Resolution": "4K",
      "Lighting": "High-power LED",
      "Lighting Forms": "Reflection and transmission",
      "Observation Modes": "Bright field, dark field, DIC, polarized light",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/china-top-of-digital-metallographic-microscope-tvn-mt4k80_p441.html",
  },
  {
    id: 9,
    name: "Digital Metallographic Microscope",
    model: "TVN-MT60_B",
    category: "metallographic-microscope",
    subCategory: "Digital Metallographic Microscope",
    resolution: "HD",
    interface: "HDMI",
    shutter: "Rolling Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.7,
    reviews: 92,
    image: "/images/products/tvn-mt60-b/main.jpg",
    images: [
      "/images/products/tvn-mt60-b/main.jpg",
      "/images/products/tvn-mt60-b/detail1.jpg",
    ],
    description: "Electron Metallographic Digital Microscope with stable atmosphere and flexible operation. Integrates bright field, dark field, polarized light, and DIC differential interference observation functions.",
    features: [
      "Stable atmosphere design",
      "Flexible operation",
      "Bright field observation",
      "Dark field observation",
      "Polarized light observation",
      "DIC differential interference",
    ],
    specs: {
      "Model": "TVN-MT60_B",
      "Observation Functions": "Bright field, dark field, polarized light, DIC",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/china-best-of-digital-metallographic-microscope-tvn-mt60-b_p406.html",
  },

  // ========== Measuring Microscopes (3 products) ==========
  {
    id: 10,
    name: "AI Image Measuring Instrument",
    model: "AI-Image-Measure",
    category: "measuring-microscope",
    subCategory: "AI Measuring Instrument",
    resolution: "High-definition",
    interface: "USB",
    shutter: "Global Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    badge: "AI Powered",
    badgeColor: "bg-violet-500",
    rating: 4.9,
    reviews: 68,
    image: "/images/products/ai-image-measure/main.jpg",
    images: [
      "/images/products/ai-image-measure/main.jpg",
      "/images/products/ai-image-measure/detail1.jpg",
    ],
    description: "AI Image Measuring Instrument with AI-guided intelligent capture and edge grabbing algorithms. Automatic recognition and measurement of all surface feature boundaries for high-end manufacturing.",
    features: [
      "AI-guided intelligent capture",
      "Edge grabbing algorithms",
      "Automatic recognition",
      "Automatic measurement",
      "Surface feature boundary detection",
      "High-end manufacturing ready",
    ],
    specs: {
      "Model": "AI Image Measuring Instrument",
      "Technology": "AI-guided intelligent capture",
      "Algorithm": "Edge grabbing algorithms",
      "Function": "Automatic recognition and measurement",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/china-top-of-ai-image-measuring-instrument_p461.html",
  },
  {
    id: 11,
    name: "Autofocus Digital Microscope",
    model: "TVN-3500AF",
    category: "measuring-microscope",
    subCategory: "Autofocus Microscope",
    resolution: "HD",
    interface: "HDMI",
    shutter: "Rolling Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    badge: "Hot",
    badgeColor: "bg-red-500",
    rating: 4.8,
    reviews: 203,
    image: "/images/products/tvn-3500af/main.jpg",
    images: [
      "/images/products/tvn-3500af/main.jpg",
      "/images/products/tvn-3500af/detail1.jpg",
    ],
    description: "Autofocus Digital Microscope with built-in precision optical focusing system. Real-time auto-focus with fast software algorithm, no manual adjustment needed within adjustable range.",
    features: [
      "Built-in precision optical focusing",
      "All-in-one design",
      "Fast software algorithm",
      "Real-time auto-focus",
      "No manual adjustment needed",
      "Precise picture rendering",
    ],
    specs: {
      "Model": "TVN-3500AF",
      "Focusing System": "Built-in precision optical",
      "Algorithm": "Fast software algorithm",
      "Focus": "Real-time auto-focus",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/china-best-of-autofocus-digital-microscope-tvn-3500af_p395.html",
  },
  {
    id: 12,
    name: "Digital Measuring Microscope",
    model: "TVN-3800II",
    category: "measuring-microscope",
    subCategory: "Digital Measuring Microscope",
    resolution: "HD",
    interface: "HDMI",
    shutter: "Rolling Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.7,
    reviews: 115,
    image: "/images/products/tvn-3800ii/main.jpg",
    images: [
      "/images/products/tvn-3800ii/main.jpg",
      "/images/products/tvn-3800ii/detail1.jpg",
    ],
    description: "Video microscope solution for industrial inspection. Ergonomic design focusing on operator comfort and wafer safety for successful integration into production lines.",
    features: [
      "Video microscope solution",
      "Ergonomic design",
      "Operator comfort focused",
      "Wafer safety features",
      "Production line integration",
    ],
    specs: {
      "Model": "TVN-3800II",
      "Type": "Video measuring microscope",
      "Ergonomic Design": "Yes",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/china-top-of-digital-measuring-microscope-tvn-3800ii_p391.html",
  },

  // ========== Electronic Microscopes (4 products) ==========
  {
    id: 13,
    name: "All-in-One Digital Microscope",
    model: "TVN-600II",
    category: "electronic-microscope",
    subCategory: "All-in-One Microscope",
    resolution: "HD",
    interface: "USB",
    shutter: "Rolling Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    badge: "New",
    badgeColor: "bg-green-500",
    rating: 4.8,
    reviews: 178,
    image: "/images/products/tvn-600ii/main.jpg",
    images: [
      "/images/products/tvn-600ii/main.jpg",
      "/images/products/tvn-600ii/detail1.jpg",
    ],
    description: "All-in-one digital microscope with magnification knob, ring light source, up and down adjustment, and USB mouse operation with U disk storage.",
    features: [
      "All-in-one design",
      "Magnification adjustment knob",
      "Ring light source",
      "Up and down adjustment",
      "Light source brightness control",
      "USB mouse operation",
      "U disk storage",
    ],
    specs: {
      "Model": "TVN-600II",
      "Magnification": "Adjustable knob",
      "Light Source": "Ring light",
      "Adjustment": "Up and down knob",
      "Storage": "U disk",
      "Control": "USB mouse",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/china-top-of-all-in-one-microscope-tvn-600ii_p403.html",
  },
  {
    id: 14,
    name: "Electronic Microscope",
    model: "TR-MS8001",
    category: "electronic-microscope",
    subCategory: "Electronic Microscope",
    resolution: "HD",
    interface: "HDMI",
    shutter: "Rolling Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.6,
    reviews: 89,
    image: "/images/products/tr-ms8001/main.jpg",
    images: [
      "/images/products/tr-ms8001/main.jpg",
      "/images/products/tr-ms8001/detail1.jpg",
    ],
    description: "Electron Microscope for PCB board inspection, QC department, and university education. Versatile and reliable for various inspection applications.",
    features: [
      "PCB board inspection",
      "QC department ready",
      "Educational use",
      "Versatile applications",
    ],
    specs: {
      "Model": "TR-MS8001",
      "Application": "PCB inspection, QC, education",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/top-of-microscope-electron-tr-ms8001_p318.html",
  },
  {
    id: 15,
    name: "Industrial Electronic Microscope",
    model: "TVN-600",
    category: "electronic-microscope",
    subCategory: "Industrial Electronic Microscope",
    resolution: "HD",
    interface: "HDMI",
    shutter: "Rolling Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    badge: "Hot",
    badgeColor: "bg-red-500",
    rating: 4.8,
    reviews: 234,
    image: "/images/products/tvn-600/main.jpg",
    images: [
      "/images/products/tvn-600/main.jpg",
      "/images/products/tvn-600/detail1.jpg",
    ],
    description: "Electronic Microscope for Inspection & Measuring with graphic overlay, HDMI camera, and video microscope functionality. Designed for PCB board inspection.",
    features: [
      "Graphic overlay function",
      "HDMI camera output",
      "Video microscope",
      "Inspection and measuring",
      "PCB board inspection ready",
    ],
    specs: {
      "Model": "TVN-600",
      "Features": "Graphic overlay, HDMI camera, video microscope",
      "Application": "Inspection and measuring",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/china-best-industrial-electronic-microscope-with-monitor-for-pcb-board-inspection-job_p189.html",
  },
  {
    id: 16,
    name: "Deep View Electronic Microscope",
    model: "TVN-S6000NMX",
    category: "electronic-microscope",
    subCategory: "Deep View Microscope",
    resolution: "1920 x 1080",
    interface: "Network",
    shutter: "Global Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.7,
    reviews: 76,
    image: "/images/products/tvn-s6000nmx/main.jpg",
    images: [
      "/images/products/tvn-s6000nmx/main.jpg",
      "/images/products/tvn-s6000nmx/detail1.jpg",
    ],
    description: "Electronic Microscope with deep view capability for detailed inspection. Features high resolution 1920x1080, high frame rate 60fps, and large 1/1.2 inch sensor.",
    features: [
      "Deep view capability",
      "1920x1080 high resolution",
      "60fps high frame rate",
      "Large 1/1.2 inch sensor",
      "Network interface",
    ],
    specs: {
      "Model": "TVN-S6000NMX",
      "Resolution": "1920 x 1080",
      "Frame Rate": "60fps",
      "Optical Size": "1/1.2\"",
      "Network Interface": "100MB/s",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/troy-vn-brand-of-deep-view-electronic-microscope_p443.html",
  },

  // ========== Vision Inspection (4 products) ==========
  {
    id: 17,
    name: "One-button MINI AOI Machine",
    model: "TR-A100",
    category: "vision-inspection",
    subCategory: "AOI Machine",
    resolution: "High-definition",
    interface: "USB",
    shutter: "Global Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    badge: "New",
    badgeColor: "bg-green-500",
    rating: 4.8,
    reviews: 145,
    image: "/images/products/tr-a100/main.jpg",
    images: [
      "/images/products/tr-a100/main.jpg",
      "/images/products/tr-a100/detail1.jpg",
    ],
    description: "One-button measuring Mini AOI widely used in machinery, electronics, mold making, injection molding, metals, rubber, low-voltage electrical appliances, and more.",
    features: [
      "One-button measurement",
      "Automatic inspection",
      "Mini size",
      "Easy operation",
      "Wide industry application",
    ],
    specs: {
      "Model": "TR-A100",
      "Type": "One-button measuring AOI",
      "Measurement": "Automatic",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/one-button-mini-aoi-machine-tr-a100_p511.html",
  },
  {
    id: 18,
    name: "Smart Vision Camera",
    model: "TVN-SmartGo",
    category: "vision-inspection",
    subCategory: "Smart Vision Camera",
    resolution: "1600 x 1400",
    interface: "HDMI/Network",
    shutter: "Global Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    badge: "Smart",
    badgeColor: "bg-violet-500",
    rating: 4.9,
    reviews: 312,
    image: "/images/products/tvn-smartgo/main.jpg",
    images: [
      "/images/products/tvn-smartgo/main.jpg",
      "/images/products/tvn-smartgo/detail1.jpg",
    ],
    description: "Smart Vision Inspection Camera with multiple interfaces and storage options. Features color/black and white modes, HDMI output, and U-disk storage.",
    features: [
      "1600 x 1400 resolution",
      "Color/Black and White modes",
      "100Mbps network interface",
      "HDMI video output",
      "IO/RS232 interfaces",
      "Dual USB ports",
      "U-disk storage",
    ],
    specs: {
      "Model": "TVN-SmartGo",
      "Resolution": "1600 x 1400",
      "Frame Rate": "Color/Black and White",
      "Network Interface": "100Mbps",
      "Video Interface": "HDMI",
      "IO Interface": "IO, RS232, power",
      "USB Interface": "2 ports",
      "Storage": "U disk",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/china-top-of-smart-vision-camera-tvn-smartgo_p446.html",
  },
  {
    id: 19,
    name: "Robot Vision Camera",
    model: "Robot-Vision-Cam",
    category: "vision-inspection",
    subCategory: "Robot Vision Camera",
    resolution: "High-definition",
    interface: "Ethernet",
    shutter: "Global Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.7,
    reviews: 98,
    image: "/images/products/robot-vision-cam/main.jpg",
    images: [
      "/images/products/robot-vision-cam/main.jpg",
      "/images/products/robot-vision-cam/detail1.jpg",
    ],
    description: "Industrial Robot Vision Camera for industrial robots vision system, defect product inspection, product position controls, and QC checking for micro products.",
    features: [
      "Industrial robot vision system",
      "Machine vision system",
      "Defect product inspection",
      "Product position control",
      "QC checking for micro products",
    ],
    specs: {
      "Model": "Robot Vision Camera",
      "Application": "Industrial robot vision, machine vision",
      "Functions": "Defect inspection, position control",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/china-industrial-robot-vision-camera-supplier_p220.html",
  },
  {
    id: 20,
    name: "PCB Microscope",
    model: "TVN-9218/9118",
    category: "vision-inspection",
    subCategory: "PCB Microscope",
    resolution: "1920 x 1080",
    interface: "HDMI",
    shutter: "Rolling Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    badge: "Hot",
    badgeColor: "bg-red-500",
    rating: 4.8,
    reviews: 267,
    image: "/images/products/tvn-9218-9118/main.jpg",
    images: [
      "/images/products/tvn-9218-9118/main.jpg",
      "/images/products/tvn-9218-9118/detail1.jpg",
    ],
    description: "Electron Microscope designed for PCB board inspection with high resolution and frame rate. Features HDMI output and SD card storage.",
    features: [
      "1920x1080 high resolution",
      "60fps high frame rate",
      "HDMI output",
      "SD card storage",
      "PCB board inspection optimized",
    ],
    specs: {
      "Model": "TVN-9218/9118",
      "Resolution": "1920 x 1080",
      "Frame Rate": "60fps",
      "Optical Size": "1/3 inch",
      "Video Interface": "HDMI",
      "USB Interface": "1",
      "Storage": "SD Card",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/china-top-of-pcb-microscope-tvn-9218-9118_p515.html",
  },

  // ========== Thermal Cameras (2 products) ==========
  {
    id: 21,
    name: "Wireless Thermal Camera",
    model: "TR-IX2 Pro",
    category: "thermal-camera",
    subCategory: "Wireless Thermal Camera",
    resolution: "256x192 (512x384 AI)",
    interface: "Wireless",
    shutter: "Rolling Shutter",
    fps: "25Hz",
    price: "Contact Us",
    priceNum: 0,
    badge: "New",
    badgeColor: "bg-green-500",
    rating: 4.8,
    reviews: 189,
    image: "/images/products/tr-ix2-pro/main.jpg",
    images: [
      "/images/products/tr-ix2-pro/main.jpg",
      "/images/products/tr-ix2-pro/detail1.jpg",
    ],
    description: "Wireless Infrared Thermal Imager for mobile phones compatible with Android and iOS. Features 256×192 thermal resolution upgradable to 512×384 via AI, 30m wireless range, and 7mm adjustable focus lens.",
    features: [
      "Wireless transmission up to 30m",
      "256×192 thermal resolution",
      "4x AI real-time super-resolution to 512×384",
      "7mm adjustable focus lens",
      "AI voice interaction",
      "Android & iOS compatible",
    ],
    specs: {
      "Model": "TR-IX2 Pro",
      "Thermal Resolution": "256×192 (512×384 with AI)",
      "Wireless Range": "30m",
      "Lens": "7mm adjustable focus",
      "Compatibility": "Android & iOS",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/china-top-of-handhold-wireless-thermal-camera_p526.html",
  },
  {
    id: 22,
    name: "Thermal Imaging Camera",
    model: "TR-460TC",
    category: "thermal-camera",
    subCategory: "Online Thermal Camera",
    resolution: "640x512",
    interface: "Network",
    shutter: "Rolling Shutter",
    fps: "25Hz",
    price: "Contact Us",
    priceNum: 0,
    badge: "4K Thermal",
    badgeColor: "bg-orange-500",
    rating: 4.9,
    reviews: 124,
    image: "/images/products/tr-460tc/main.jpg",
    images: [
      "/images/products/tr-460tc/main.jpg",
      "/images/products/tr-460tc/detail1.jpg",
    ],
    description: "High-performance network-based thermal imager with uncooled infrared focal plane array detector. Supports Modbus TCP, ONVIF, and GB28181 protocols with professional analysis software and SDK.",
    features: [
      "640×512 high resolution",
      "25Hz frame rate",
      "-20℃ to +650℃ temperature range",
      "Modbus TCP, ONVIF, GB28181 support",
      "Multiple lens options",
      "Temperature compensation algorithm",
      "Professional analysis software & SDK",
    ],
    specs: {
      "Model": "TR-460TC",
      "Resolution": "640×512",
      "Frame Rate": "25Hz",
      "Temperature Range": "-20℃ to +650℃",
      "Protocols": "Modbus TCP, ONVIF, GB28181",
      "Detector": "Uncooled infrared focal plane array",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/china-best-of-thermal-imaging-camera-tr-460tc_p525.html",
  },

  // ========== Specialized Microscopes (2 products) ==========
  {
    id: 23,
    name: "Depth of Field Microscope",
    model: "TVN-600II_A",
    category: "specialized-microscope",
    subCategory: "Depth of Field Microscope",
    resolution: "HD",
    interface: "Ethernet",
    shutter: "Rolling Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    badge: "Hot",
    badgeColor: "bg-red-500",
    rating: 4.8,
    reviews: 156,
    image: "/images/products/tvn-600ii-a/main.jpg",
    images: [
      "/images/products/tvn-600ii-a/main.jpg",
      "/images/products/tvn-600ii-a/detail1.jpg",
    ],
    description: "Electric Microscope with flashlight function, depth of field synthesis, light source shielding, and Ethernet port for convenient picture transfer.",
    features: [
      "Flashlight function for unclear fonts",
      "Depth of field synthesis",
      "Light source shielding for FPC boards",
      "Ethernet port for picture transfer",
      "PCBA chip inspection",
      "FPC board observation",
    ],
    specs: {
      "Model": "TVN-600II_A",
      "Functions": "Flashlight, Depth of field synthesis, Light source shielding",
      "Interface": "Ethernet port",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/world-top-of-depth-of-field-microscope-tvn-600ii_p474.html",
  },
  {
    id: 24,
    name: "SEM Microscope",
    model: "TR3200",
    category: "specialized-microscope",
    subCategory: "SEM Microscope",
    resolution: "Nanometer scale",
    interface: "USB",
    shutter: "Rolling Shutter",
    fps: "N/A",
    price: "Contact Us",
    priceNum: 0,
    badge: "Premium",
    badgeColor: "bg-purple-500",
    rating: 4.9,
    reviews: 45,
    image: "/images/products/tr3200/main.jpg",
    images: [
      "/images/products/tr3200/main.jpg",
      "/images/products/tr3200/detail1.jpg",
    ],
    description: "High-performance tungsten SEM microscope with excellent image quality in both high and low vacuum modes. Large depth of field and user-friendly interface for sample characterization.",
    features: [
      "High-performance tungsten SEM",
      "High and low vacuum modes",
      "Large depth of field",
      "User-friendly interface",
      "Sample characterization",
      "Nanometer scale imaging",
    ],
    specs: {
      "Model": "TR3200",
      "Type": "Tungsten SEM",
      "Vacuum Modes": "High and low vacuum",
      "Features": "Large depth of field",
      "Resolution": "Nanometer scale",
    },
    inStock: true,
    detailUrl: "https://www.troysupply.com/china-top-of-sem-microscope-tr3200_p458.html",
  },
];
