export interface Product {
  id: number;
  name: string;
  model: string;
  category: string;
  subCategory: string;
  resolution: string;
  interface: string;
  shutter: string;
  fps: string;
  price: string;
  priceNum: number;
  badge?: string;
  badgeColor?: string;
  rating: number;
  reviews: number;
  image?: string;
  images?: string[];
  description: string;
  features: string[];
  specs: Record<string, string>;
  inStock: boolean;
  detailUrl?: string;
}

export const categories = [
  { id: "hdmi", name: "HDMI Cameras", count: 9 },
  { id: "vga", name: "VGA Cameras", count: 1 },
  { id: "digital-microscope", name: "Digital Microscopes", count: 1 },
  { id: "vision-inspection", name: "Vision Inspection", count: 1 },
  { id: "microscope", name: "Microscope Cameras", count: 9 },
  { id: "smart", name: "Smart Cameras", count: 8 },
];

export const products: Product[] = [
  {
    id: 20,
    name: "Smart Vision Inspection Camera",
    model: "SmartGO-570CPLC",
    category: "smart",
    subCategory: "Smart Camera",
    resolution: "1600 x 1200",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    badge: "Hot",
    badgeColor: "bg-red-500",
    rating: 4.9,
    reviews: 328,
    image: "/images/products/smartgo-570cplc/front.jpg",
    images: [
      "/images/products/smartgo-570cplc/front.jpg",
      "/images/products/smartgo-570cplc/back.jpg",
      "/images/products/smartgo-570cplc/dimension-front.jpg",
      "/images/products/smartgo-570cplc/dimension-back.jpg",
      "/images/products/smartgo-570cplc/detail-specs.jpg",
    ],
    description: "SmartGO-570CPLC Smart Vision Inspection Camera, 1600x1200 resolution, supports HDMI output, network interface, USB storage, suitable for industrial inspection and machine vision applications.",
    features: [
      "1600 x 1200 High Resolution",
      "HDMI HD Output",
      "100/1000Mbps Network Interface",
      "6 Groups IO/RS232 Interface",
      "2 USB Ports, Support USB Flash Drive",
      "FPGA+ARM Dual-Core Processing",
      "LINUX Operating System",
      "C-Mount Lens",
    ],
    specs: {
      "Model": "SmartGO-570CPLC",
      "Resolution": "1600 x 1200 x 24bit",
      "Color": "Color/Mono",
      "Frame Rate": "60fps",
      "Sensor Size": "1/1.8\"",
      "Pixel Size": "5.3 x 5.3 μm",
      "Shutter Type": "Global Shutter",
      "Color Adjustment": "R, G, B Independent Adjustment",
      "Exposure Mode": "Auto Exposure",
      "WDR": "Supported",
      "Chip Architecture": "FPGA+ARM",
      "Operating System": "LINUX",
      "Core Architecture": "Dual-Core Cortex-A9",
      "I/O Interface": "6 Groups IO/RS232",
      "Network Interface": "100/1000Mbps",
      "USB Interface": "2 USB Ports",
      "Storage Mode": "USB Flash Drive",
      "Lens Mount": "C-Mount",
      "Display Interface": "HDMI",
      "Operation Mode": "Mouse Operation",
      "Power Supply": "DC 12V-24V",
      "Dimensions": "71x71x78 mm",
      "Weight": "350g",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=20",
  },
  {
    id: 16,
    name: "Multi-function HD Camera",
    model: "Smart-6000X",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Color",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 0,
    image: "/images/products/工业相机-主图/2-多功能高清相机(Smart-6000X)/Smart-6000XM (1).png",
    images: ["/images/products/工业相机-主图/2-多功能高清相机(Smart-6000X)/Smart-6000XM (1).png","/images/products/工业相机-主图/2-多功能高清相机(Smart-6000X)/Smart-6000XM (2).png"],
    
    description: "Multi-function HD camera with 1920 X 1080 resolution and HDMI interface",
    features: ["1920 X 1080 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "1920 X 1080",
      "Video Interface": "HDMI",
      "Network Interface": "100Mbps",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=16",
  },
  {
    id: 46,
    name: "Large Field of View Auto Focus Camera",
    model: "3500AF",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    badge: "Hot",
    badgeColor: "bg-red-500",
    rating: 4.9,
    reviews: 156,
    image: "/images/products/工业相机-主图/3-大视野相机3500AF/3500AF (1).png",
    images: [
      "/images/products/工业相机-主图/3-大视野相机3500AF/3500AF (1).png",
      "/images/products/工业相机-主图/3-大视野相机3500AF/3500AF (2).png",
      "/images/products/3500af/detail-full.jpg"
    ],
    description: "3500AF Large Field of View Auto Focus Industrial Camera, 1920x1080 resolution, precision optical auto focus system with fast software algorithm for real-time auto focus. Features 3 focus modes (full screen, center, spot), 14x optical zoom, video recording, and USB storage.",
    features: [
      "1920 X 1080 Full HD Resolution",
      "Precision Optical Auto Focus System",
      "3 Focus Modes: Full Screen/Center/Spot",
      "14X Optical Zoom (0.65X-3.3X)",
      "60fps High Frame Rate",
      "Video Recording Function",
      "USB Flash Drive Storage",
      "HIS+ARM Dual-Core Architecture",
      "Linux Operating System",
      "Wide Field of View: 310mm-38mm"
    ],
    specs: {
      "Model": "3500AF",
      "Resolution": "1920 X 1080",
      "Sensor Size": "1/3\"",
      "Optical Zoom": "14X (0.65X-3.3X)",
      "Frame Rate": "60fps",
      "Focus Modes": "Full Screen / Center / Spot",
      "Min FOV": "310mm (0.65X)",
      "Max FOV": "38mm (3.3X)",
      "Chip Architecture": "HIS+ARM",
      "Core Architecture": "Dual-Core Cortex-A9",
      "Operating System": "Linux 3.10",
      "Main Frequency": "1GHz",
      "Video Interface": "HDMI",
      "Storage": "USB Flash Drive",
      "Video Recording": "Supported",
      "Working Voltage": "DC 12V",
      "Working Temperature": "-10~70°C",
      "Dimensions": "70x70x140 mm",
      "Weight": "300g"
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=46",
  },
  {
    id: 63,
    name: "Smart-6500 Microscope Camera",
    model: "Smart-6500",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Color",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/4-Smart-6500显微镜相机/Smart-6500 (1).png",
    images: ["/images/products/工业相机-主图/4-Smart-6500显微镜相机/Smart-6500 (1).png","/images/products/工业相机-主图/4-Smart-6500显微镜相机/Smart-6500 (2).png"],
    
    rating: 4.8,
    reviews: 0,
    description: "Smart-6500 microscope camera with 1920 X 1080 resolution and HDMI interface",
    features: ["1920 X 1080 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "1920 X 1080",
      "Video Interface": "HDMI",
      "Network Interface": "N/A",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=63",
  },
  {
    id: 64,
    name: "Smart-6500M Microscope Camera",
    model: "Smart-6500M",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Color",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/5-Smart-6500M显微镜相机/Smart-6500M.png",
    images: ["/images/products/工业相机-主图/5-Smart-6500M显微镜相机/Smart-6500M.png","/images/products/工业相机-主图/5-Smart-6500M显微镜相机/Smart-6500M.jpg"],
    
    rating: 4.8,
    reviews: 0,
    description: "Smart-6500M microscope camera with 1920 X 1080 resolution and HDMI interface",
    features: ["1920 X 1080 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "1920 X 1080",
      "Video Interface": "HDMI",
      "Network Interface": "N/A",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=64",
  },
  {
    id: 6,
    name: "HDMI HD Camera",
    model: "UC-9185",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Color",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/6-HDMI高清相机(SS-9185)/SS-9185 (1).png",
    images: [
      "/images/products/工业相机-主图/6-HDMI高清相机(SS-9185)/SS-9185 (1).png",
      "/images/products/工业相机-主图/6-HDMI高清相机(SS-9185)/SS-9185 (2).png",
      "/images/products/uc-9185/detail-full.jpg"
    ],
    rating: 4.8,
    reviews: 128,
    description: "UC-9185 2MP HDMI Industrial Camera, 1920x1080 resolution, 60fps high frame rate, FPGA+ARM dual-core architecture, supports SD card storage, edge enhancement, HDR wide dynamic range, and independent color adjustment.",
    features: [
      "1920 X 1080 Full HD Resolution",
      "60fps High Frame Rate",
      "FPGA+ARM Dual-Core Architecture",
      "Linux 3.10 Operating System",
      "SD Card Storage Support",
      "Edge Enhancement",
      "HDR Wide Dynamic Range",
      "Independent Color Adjustment",
      "White Balance Adjustment",
      "Auto Exposure Adjustment"
    ],
    specs: {
      "Model": "UC-9185 (SMART-3000)",
      "Resolution": "1920 X 1080",
      "Frame Rate": "60fps",
      "Sensor Size": "1/2\"",
      "Pixel Size": "3.75μm × 3.75μm",
      "Chip Architecture": "FPGA+ARM",
      "Core Architecture": "Dual-Core Cortex-A9",
      "Operating System": "Linux 3.10",
      "Main Frequency": "666MHz",
      "Video Interface": "HDMI",
      "USB Interface": "2 USB Ports",
      "Storage": "SD Card",
      "Lens Mount": "C-Mount",
      "Working Voltage": "DC 5-12V",
      "Working Temperature": "-10℃ ~ 70℃",
      "Dimensions": "61×61×72 mm",
      "Weight": "350g"
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=6",
  },
  {
    id: 18,
    name: "2MP Smart Camera",
    model: "SmartGO-185",
    category: "smart",
    subCategory: "Smart Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Color",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/7-200万智能相机（SmartGO-185）/SmartGO-185CPLC (1).jpg",
    images: ["/images/products/工业相机-主图/7-200万智能相机（SmartGO-185）/SmartGO-185CPLC (1).jpg","/images/products/工业相机-主图/7-200万智能相机（SmartGO-185）/SmartGO-185CPLC (2).jpg"],
    
    rating: 4.8,
    reviews: 0,
    description: "2MP smart camera with 1920 X 1080 resolution and HDMI interface",
    features: ["1920 X 1080 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "1920 X 1080",
      "Video Interface": "HDMI",
      "Network Interface": "100Mbps",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=18",
  },
  {
    id: 59,
    name: "Smart-4k-80 HD Microscope Camera",
    model: "Smart-4k-80",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "3840 X 2160",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/8-Smart-4k-80高清显微镜相机/Smart-4K80M.jpg",
    images: ["/images/products/工业相机-主图/8-Smart-4k-80高清显微镜相机/Smart-4K80M.jpg"],
    
    rating: 4.8,
    reviews: 0,
    description: "Smart-4k-80 HD microscope camera with 3840 X 2160 resolution and HDMI interface",
    features: ["3840 X 2160 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "3840 X 2160",
      "Video Interface": "HDMI",
      "Network Interface": "100Mbps",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=59",
  },
  {
    id: 17,
    name: "2K Ultra HD Camera",
    model: "Smart-2K",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "2560 X 1440",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Color",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/9-2K超清相机(Smart-2K)/Smart-2KM (1).png",
    images: ["/images/products/工业相机-主图/9-2K超清相机(Smart-2K)/Smart-2KM (1).png","/images/products/工业相机-主图/9-2K超清相机(Smart-2K)/Smart-2KM (2).png","/images/products/工业相机-主图/9-2K超清相机(Smart-2K)/Smart-2KM (3).png"],
    
    rating: 4.8,
    reviews: 0,
    description: "2K ultra HD camera with 2560 X 1440 resolution and HDMI interface",
    features: ["2560 X 1440 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "2560 X 1440",
      "Video Interface": "HDMI",
      "Network Interface": "None",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=17",
  },
  {
    id: 41,
    name: "4K Camera",
    model: "UC-4K",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "3840 X 2160",
    interface: "USB",
    shutter: "Global Shutter",
    fps: "30fps",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/10-4k相机/Smart-4k (1).png",
    images: ["/images/products/工业相机-主图/10-4k相机/Smart-4k (1).png","/images/products/工业相机-主图/10-4k相机/Smart-4k (2).png","/images/products/工业相机-主图/10-4k相机/Smart-4k (3).png"],
    
    rating: 4.8,
    reviews: 0,
    description: "4K camera with 3840 X 2160 resolution and USB interface",
    features: ["3840 X 2160 High Resolution", "USB Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "3840 X 2160",
      "Video Interface": "USB",
      "Network Interface": "N/A",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=41",
  },
  {
    id: 60,
    name: "2MP HDMI Camera",
    model: "HDMI-2MP",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/11-200万HDMI相机/HD-200 (1).jpg",
    images: ["/images/products/工业相机-主图/11-200万HDMI相机/HD-200 (1).jpg","/images/products/工业相机-主图/11-200万HDMI相机/HD-200 (2).jpg"],
    
    rating: 4.8,
    reviews: 0,
    description: "2MP HDMI camera with 1920 X 1080 resolution and HDMI interface",
    features: ["1920 X 1080 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "1920 X 1080",
      "Video Interface": "HDMI",
      "Network Interface": "N/A",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=60",
  },
  {
    id: 61,
    name: "2MP Pixel HDMI Camera",
    model: "HDMI-2MP-Pro",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Color",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/12-200万像素HDMI相机/HD500.png",
    images: ["/images/products/工业相机-主图/12-200万像素HDMI相机/HD500.png"],
    
    rating: 4.8,
    reviews: 0,
    description: "2MP pixel HDMI camera with 1920 X 1080 resolution and HDMI interface",
    features: ["1920 X 1080 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "1920 X 1080",
      "Video Interface": "HDMI",
      "Network Interface": "N/A",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=61",
  },
  {
    id: 25,
    name: "6MP B/W Vision Inspection Camera",
    model: "SmartGO-6MP-BW",
    category: "smart",
    subCategory: "Smart Camera",
    resolution: "3072 x 1728",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Mono",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/13-600万黑白视觉检测相机/SmartGO-178MPLC (1).png",
    images: ["/images/products/工业相机-主图/13-600万黑白视觉检测相机/SmartGO-178MPLC (1).png","/images/products/工业相机-主图/13-600万黑白视觉检测相机/SmartGO-178MPLC (2).png","/images/products/工业相机-主图/13-600万黑白视觉检测相机/SmartGO-178MPLC (3).jpg","/images/products/工业相机-主图/13-600万黑白视觉检测相机/SmartGO-178MPLC (4).jpg"],
    
    rating: 4.8,
    reviews: 0,
    description: "6MP black and white vision inspection camera with 3072 x 1728 resolution and HDMI interface",
    features: ["3072 x 1728 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "3072 x 1728",
      "Video Interface": "HDMI",
      "Network Interface": "100Mbps",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=25",
  },
  {
    id: 19,
    name: "6MP Smart Inspection Camera",
    model: "SmartGO-178CPLC",
    category: "smart",
    subCategory: "Smart Camera",
    resolution: "3072 x 1728",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Color",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/14-600万智能检测相机(SmartGO-178CPLC)/SmartGO-178CPLC (1).jpg",
    images: ["/images/products/工业相机-主图/14-600万智能检测相机(SmartGO-178CPLC)/SmartGO-178CPLC (1).jpg","/images/products/工业相机-主图/14-600万智能检测相机(SmartGO-178CPLC)/SmartGO-178CPLC (2).jpg"],
    
    rating: 4.8,
    reviews: 0,
    description: "6MP smart inspection camera with 3072 x 1728 resolution and HDMI interface",
    features: ["3072 x 1728 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "3072 x 1728",
      "Video Interface": "HDMI",
      "Network Interface": "100Mbps",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=19",
  },
  {
    id: 12,
    name: "HDMI HD Measurement Camera",
    model: "Smart-2000M",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Color",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/15-HDMI高清测量相机(Smart-2000M)/Smart-2000M (1).png",
    images: ["/images/products/工业相机-主图/15-HDMI高清测量相机(Smart-2000M)/Smart-2000M (1).png","/images/products/工业相机-主图/15-HDMI高清测量相机(Smart-2000M)/Smart-2000M (2).png","/images/products/工业相机-主图/15-HDMI高清测量相机(Smart-2000M)/Smart-2000M (3).png","/images/products/工业相机-主图/15-HDMI高清测量相机(Smart-2000M)/Smart-2000M (4).png"],
    
    rating: 4.8,
    reviews: 0,
    description: "HDMI HD measurement camera with 1920 X 1080 resolution and HDMI interface",
    features: ["1920 X 1080 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "1920 X 1080",
      "Video Interface": "HDMI",
      "Network Interface": "None",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=12",
  },
  {
    id: 8,
    name: "HDMI HD Camera",
    model: "Smart-2000",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Color",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/16-HDMI高清相机(Smart-2000)/Smart-2000 (1).png",
    images: ["/images/products/工业相机-主图/16-HDMI高清相机(Smart-2000)/Smart-2000 (1).png","/images/products/工业相机-主图/16-HDMI高清相机(Smart-2000)/Smart-2000 (2).png"],
    
    rating: 4.8,
    reviews: 0,
    description: "HDMI HD camera with 1920 X 1080 resolution and HDMI interface",
    features: ["1920 X 1080 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "1920 X 1080",
      "Video Interface": "HDMI",
      "Network Interface": "None",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=8",
  },
  {
    id: 9,
    name: "HDMI HD Camera",
    model: "Smart-3000",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Color",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/17-HDMI高清相机(Smart-3000)/Smart-3000 (1).png",
    images: ["/images/products/工业相机-主图/17-HDMI高清相机(Smart-3000)/Smart-3000 (1).jpg","/images/products/工业相机-主图/17-HDMI高清相机(Smart-3000)/Smart-3000 (1).png","/images/products/工业相机-主图/17-HDMI高清相机(Smart-3000)/Smart-3000 (2).png"],
    
    rating: 4.8,
    reviews: 0,
    description: "HDMI HD camera with 1920 X 1080 resolution and HDMI interface",
    features: ["1920 X 1080 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "1920 X 1080",
      "Video Interface": "HDMI",
      "Network Interface": "None",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=9",
  },
  {
    id: 69,
    name: "HS-3500M Microscope Camera",
    model: "HS-3500M",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/18-HS-3500M显微镜相机/HS-3500M.png",
    images: ["/images/products/工业相机-主图/18-HS-3500M显微镜相机/HS-3500M.png"],
    
    rating: 4.8,
    reviews: 0,
    description: "HS-3500M microscope camera with 1920 X 1080 resolution and HDMI interface",
    features: ["1920 X 1080 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "1920 X 1080",
      "Video Interface": "HDMI",
      "Network Interface": "N/A",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=69",
  },
  {
    id: 68,
    name: "HS3500 Microscope Camera",
    model: "HS3500",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Color",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/19-HS3500显微镜相机/HS-3500 (1).jpg",
    images: ["/images/products/工业相机-主图/19-HS3500显微镜相机/HS-3500 (1).jpg","/images/products/工业相机-主图/19-HS3500显微镜相机/HS-3500 (2).jpg","/images/products/工业相机-主图/19-HS3500显微镜相机/HS-3500 (3).jpg"],
    
    rating: 4.8,
    reviews: 0,
    description: "HS3500 microscope camera with 1920 X 1080 resolution and HDMI interface",
    features: ["1920 X 1080 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "1920 X 1080",
      "Video Interface": "HDMI",
      "Network Interface": "N/A",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=68",
  },
  {
    id: 70,
    name: "Smart-100SE Microscope Camera",
    model: "Smart-100SE",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "30fps",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/20-Smart-100SE显微镜相机/Smart-100SE (1).png",
    images: ["/images/products/工业相机-主图/20-Smart-100SE显微镜相机/Smart-100SE (1).png","/images/products/工业相机-主图/20-Smart-100SE显微镜相机/Smart-100SE (2).png"],
    
    rating: 4.8,
    reviews: 0,
    description: "Smart-100SE microscope camera with 1920 X 1080 resolution and HDMI interface",
    features: ["1920 X 1080 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "1920 X 1080",
      "Video Interface": "HDMI",
      "Network Interface": "Yes",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=70",
  },
  {
    id: 62,
    name: "Smart-6000 Microscope Camera",
    model: "Smart-6000",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "60fps",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/21-smart-6000显微镜相机/Smart-6000 (1).png",
    images: ["/images/products/工业相机-主图/21-smart-6000显微镜相机/Smart-6000 (1).png","/images/products/工业相机-主图/21-smart-6000显微镜相机/Smart-6000 (2).png"],
    
    rating: 4.8,
    reviews: 0,
    description: "Smart-6000 microscope camera with 1920 X 1080 resolution and HDMI interface",
    features: ["1920 X 1080 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "1920 X 1080",
      "Video Interface": "HDMI",
      "Network Interface": "N/A",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=62",
  },
  {
    id: 71,
    name: "SmartGo-178PLC Vision Inspection Camera",
    model: "SmartGo-178PLC",
    category: "smart",
    subCategory: "Smart Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "30fps",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/22-SmartGo-178PLC视觉检测相机/SmartGO-178MPLC (1).png",
    images: ["/images/products/工业相机-主图/22-SmartGo-178PLC视觉检测相机/SmartGO-178MPLC (1).png","/images/products/工业相机-主图/22-SmartGo-178PLC视觉检测相机/SmartGO-178MPLC (2).png"],
    
    rating: 4.8,
    reviews: 0,
    description: "SmartGo-178PLC vision inspection camera with 1920 X 1080 resolution and HDMI interface",
    features: ["1920 X 1080 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "1920 X 1080",
      "Video Interface": "HDMI",
      "Network Interface": "Yes",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=71",
  },
  {
    id: 65,
    name: "SMARTGO-6000M",
    model: "SMARTGO-6000M",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Color",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/23-SMARTGO-6000M/Smart-6000M (1).jpg",
    images: ["/images/products/工业相机-主图/23-SMARTGO-6000M/Smart-6000M (1).jpg","/images/products/工业相机-主图/23-SMARTGO-6000M/Smart-6000M (2).jpg"],
    
    rating: 4.8,
    reviews: 0,
    description: "SMARTGO-6000M with 1920 X 1080 resolution and HDMI interface",
    features: ["1920 X 1080 High Resolution", "HDMI Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "1920 X 1080",
      "Video Interface": "HDMI",
      "Network Interface": "N/A",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=65",
  },
  {
    id: 10,
    name: "VGA Camera",
    model: "902",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "1280 X 1024",
    interface: "VGA",
    shutter: "Global Shutter",
    fps: "Color",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/24-VGA相机(902)/SS-902 (1).png",
    images: ["/images/products/工业相机-主图/24-VGA相机(902)/SS-902 (1).png","/images/products/工业相机-主图/24-VGA相机(902)/SS-902 (2).png","/images/products/工业相机-主图/24-VGA相机(902)/SS-902 (3).png","/images/products/工业相机-主图/24-VGA相机(902)/SS-902 (4).png"],
    
    rating: 4.8,
    reviews: 0,
    description: "VGA camera with 1280 X 1024 resolution and VGA interface",
    features: ["1280 X 1024 High Resolution", "VGA Interface", "Industrial Grade Reliability"],
    specs: {
      "Resolution": "1280 X 1024",
      "Video Interface": "VGA",
      "Network Interface": "None",
      "IO Interface": "N/A",
      "USB Interface": "N/A",
      "Storage": "N/A",
    },
    inStock: true,
    detailUrl: "https://www.utocom.com/pd.jsp?id=10",
  },
  // 新增产品
  {
    id: 23,
    name: "产品定位相机",
    model: "SmartGO-560M",
    category: "smart",
    subCategory: "Smart Camera",
    resolution: "1280 X 1024",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Mono",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/25-产品定位相机(SmartGO-560M)/SmartGO-560MPLC (1).png",
    images: ["/images/products/工业相机-主图/25-产品定位相机(SmartGO-560M)/SmartGO-560MPLC (1).png","/images/products/工业相机-主图/25-产品定位相机(SmartGO-560M)/SmartGO-560MPLC (2).png","/images/products/工业相机-主图/25-产品定位相机(SmartGO-560M)/SmartGO-560MPLC (3).jpg","/images/products/工业相机-主图/25-产品定位相机(SmartGO-560M)/SmartGO-560MPLC (4).jpg"],
    
    badge: "New",
    badgeColor: "#22C55E",
    rating: 4.9,
    reviews: 0,
    description: "产品定位相机 SmartGO-560M，1280x1024 分辨率，支持 HDMI 输出和 U 盘存储",
    features: ["1280 X 1024 分辨率", "HDMI 接口", "100Mbps 网络", "IO/RS232/电源接口", "U盘存储"],
    specs: {
      "Resolution": "1280 X 1024",
      "Video Interface": "HDMI",
      "Network Interface": "100Mbps",
      "IO Interface": "IO, RS232, Power",
      "USB Interface": "2 ports",
      "Storage": "USB Flash Drive",
    },
    inStock: true,
    detailUrl: "https://www.sunsightimage.com/pd.jsp?id=23",
  },
  {
    id: 13,
    name: "高清测量相机",
    model: "Smart-3000M",
    category: "hdmi",
    subCategory: "HDMI Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Color",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/26-高清测量相机(Smart-3000M)/Smart-3000M (1).png",
    images: ["/images/products/工业相机-主图/26-高清测量相机(Smart-3000M)/Smart-3000M (1).png","/images/products/工业相机-主图/26-高清测量相机(Smart-3000M)/Smart-3000M (2).png","/images/products/工业相机-主图/26-高清测量相机(Smart-3000M)/Smart-3000M (3).png","/images/products/工业相机-主图/26-高清测量相机(Smart-3000M)/Smart-3000M (4).png"],
    
    badge: "New",
    badgeColor: "#22C55E",
    rating: 4.8,
    reviews: 0,
    description: "高清测量相机 Smart-3000M，1920x1080 全高清分辨率，支持 HDMI 输出和 U 盘存储",
    features: ["1920 X 1080 全高清", "HDMI 接口", "U盘存储", "2个USB接口"],
    specs: {
      "Resolution": "1920 X 1080",
      "Video Interface": "HDMI",
      "Network Interface": "None",
      "IO Interface": "N/A",
      "USB Interface": "2 ports",
      "Storage": "USB Flash Drive",
    },
    inStock: true,
    detailUrl: "https://www.sunsightimage.com/pd.jsp?id=13",
  },
  {
    id: 22,
    name: "黑白视觉检测相机",
    model: "SmartGO-570M",
    category: "smart",
    subCategory: "Smart Camera",
    resolution: "1600 x 1400",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Color",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/27-黑白视觉检测相机(SmartGO-570M)/SmartGO-570MPLC (1).png",
    images: ["/images/products/工业相机-主图/27-黑白视觉检测相机(SmartGO-570M)/SmartGO-570MPLC (1).png","/images/products/工业相机-主图/27-黑白视觉检测相机(SmartGO-570M)/SmartGO-570MPLC (2).png","/images/products/工业相机-主图/27-黑白视觉检测相机(SmartGO-570M)/SmartGO-570MPLC (3).jpg","/images/products/工业相机-主图/27-黑白视觉检测相机(SmartGO-570M)/SmartGO-570MPLC (4).jpg"],
    
    badge: "Hot",
    badgeColor: "#EF4444",
    rating: 4.9,
    reviews: 0,
    description: "黑白视觉检测相机 SmartGO-570M，1600x1400 高分辨率，支持 HDMI 输出和 U 盘存储",
    features: ["1600 x 1400 高分辨率", "HDMI 接口", "100Mbps 网络", "IO/RS232/电源接口", "U盘存储"],
    specs: {
      "Resolution": "1600 x 1400",
      "Video Interface": "HDMI",
      "Network Interface": "100Mbps",
      "IO Interface": "IO, RS232, Power",
      "USB Interface": "2 ports",
      "Storage": "USB Flash Drive",
    },
    inStock: true,
    detailUrl: "https://www.sunsightimage.com/pd.jsp?id=22",
  },
  {
    id: 24,
    name: "视觉检测相机",
    model: "Smart-3000A",
    category: "smart",
    subCategory: "Smart Camera",
    resolution: "1920 X 1080",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Color",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/28-视觉检测相机（Smart-3000A）/SmartGO-3000A (1).jpg",
    images: ["/images/products/工业相机-主图/28-视觉检测相机（Smart-3000A）/SmartGO-3000A (1).jpg","/images/products/工业相机-主图/28-视觉检测相机（Smart-3000A）/SmartGO-3000A (2).jpg","/images/products/工业相机-主图/28-视觉检测相机（Smart-3000A）/SmartGO-3000A (1).png"],
    
    badge: "New",
    badgeColor: "#22C55E",
    rating: 4.8,
    reviews: 0,
    description: "视觉检测相机 Smart-3000A，1920x1080 全高清分辨率，支持 HDMI 输出和 U 盘存储",
    features: ["1920 X 1080 全高清", "HDMI 接口", "IO/RS232/电源接口", "2个USB接口", "U盘存储"],
    specs: {
      "Resolution": "1920 X 1080",
      "Video Interface": "HDMI",
      "Network Interface": "None",
      "IO Interface": "IO, RS232, Power",
      "USB Interface": "2 ports",
      "Storage": "USB Flash Drive",
    },
    inStock: true,
    detailUrl: "https://www.sunsightimage.com/pd.jsp?id=24",
  },
  {
    id: 21,
    name: "智能视觉检测相机130万",
    model: "SmartGO-130",
    category: "smart",
    subCategory: "Smart Camera",
    resolution: "1280 X 1024",
    interface: "HDMI",
    shutter: "Global Shutter",
    fps: "Color",
    price: "Contact Us",
    priceNum: 0,
    image: "/images/products/工业相机-主图/29-智能视觉加测相机130万/SmartGO-560CPLC (1).jpg",
    images: ["/images/products/工业相机-主图/29-智能视觉加测相机130万/SmartGO-560CPLC (1).jpg","/images/products/工业相机-主图/29-智能视觉加测相机130万/SmartGO-560CPLC (2).jpg","/images/products/工业相机-主图/29-智能视觉加测相机130万/SmartGO-560CPLC (3).jpg","/images/products/工业相机-主图/29-智能视觉加测相机130万/SmartGO-560CPLC (4).jpg"],
    
    badge: "New",
    badgeColor: "#22C55E",
    rating: 4.9,
    reviews: 0,
    description: "智能视觉检测相机130万像素，1280x1024 分辨率，支持 HDMI 输出和 U 盘存储",
    features: ["1280 X 1024 分辨率", "130万像素", "HDMI 接口", "100Mbps 网络", "IO/RS232/电源接口", "U盘存储"],
    specs: {
      "Resolution": "1280 X 1024",
      "Video Interface": "HDMI",
      "Network Interface": "100Mbps",
      "IO Interface": "IO, RS232, Power",
      "USB Interface": "2 ports",
      "Storage": "USB Flash Drive",
    },
    inStock: true,
    detailUrl: "https://www.sunsightimage.com/pd.jsp?id=21",
  },
];
