export interface Product {
  id: number;
  name: string;
  model: string;
  category: string;
  subCategory: string;
  price: string;
  priceNum: number;
  badge?: string;
  badgeColor?: string;
  rating: number;
  reviews: number;
  image?: string;
  images?: string[]; // 多张产品图片
  description: string;
  specs: Record<string, string>;
  inStock: boolean;
}

// Categories for Utocom products
export const categories = [
  { id: "3d-microscope", name: "3D Microscopes", count: 6 },
  { id: "metallographic-microscope", name: "Metallographic Microscopes", count: 3 },
  { id: "measuring-microscope", name: "Measuring Microscopes", count: 3 },
  { id: "electronic-microscope", name: "Electronic Microscopes", count: 4 },
  { id: "vision-inspection", name: "Vision Inspection", count: 4 },
  { id: "thermal-camera", name: "Thermal Cameras", count: 2 },
  { id: "specialized-microscope", name: "Specialized Microscopes", count: 2 },
];

// Products from Excel (工业相机产品清单)
export const products: Product[] = [
  {
    id: 1,
    name: "China Best Of Metallographic Tool Microscope UT-50MINI",
    model: "UT-50MINI",
    category: "metallographic-microscope",
    subCategory: "Metallographic Tool Microscope",
    price: "Contact Us",
    priceNum: 0,
    badge: "New",
    badgeColor: "bg-green-500",
    rating: 4.8,
    reviews: 110,
    image: "/images/products/ut-50mini/main.jpg",
    images: [
      "/images/products/ut-50mini/main.jpg",
      "/images/products/ut-50mini/detail1.jpg",
      "/images/products/ut-50mini/detail2.jpg",
      "/images/products/ut-50mini/detail3.jpg",
      "/images/products/ut-50mini/detail4.jpg",
      "/images/products/ut-50mini/detail5.jpg",
    ],
    description: "This product combines the high magnification of a metallographic microscope with the X, Y, and Z dimensional measurement capabilities of an image measuring instrument, making it a multifunctional measuring instrument with high-precision linear measurement and observation capabilities.",
    specs: {
      "Item No.": "UT-50MINI",
      "Payment": "EXW/FOB/CIF/DDU/DAP.",
      "Product origin": "China",
      "Color": "white",
      "Shipping port": "QingDao",
      "Lead Time": "35"
    },
    inStock: true,
  },
  {
    id: 2,
    name: "China Top Of Handhold Wireless Thermal Camera",
    model: "UT-IX2 Pro",
    category: "thermal-camera",
    subCategory: "Wireless Thermal Camera",
    price: "Contact Us",
    priceNum: 0,
    badge: "New",
    badgeColor: "bg-green-500",
    rating: 4.8,
    reviews: 120,
    image: "/images/products/ut-ix2-pro/main.jpg",
    images: [
      "/images/products/ut-ix2-pro/main.jpg",
      "/images/products/ut-ix2-pro/detail1.jpg",
      "/images/products/ut-ix2-pro/detail2.jpg",
      "/images/products/ut-ix2-pro/detail3.jpg",
      "/images/products/ut-ix2-pro/detail4.jpg",
      "/images/products/ut-ix2-pro/detail5.jpg",
      "/images/products/ut-ix2-pro/detail6.jpg",
      "/images/products/ut-ix2-pro/detail7.jpg",
      "/images/products/ut-ix2-pro/detail8.jpg",
      "/images/products/ut-ix2-pro/detail9.jpg",
      "/images/products/ut-ix2-pro/detail10.jpg"
    ],
    description: "UT-IX2 Pro is a new type of wireless infrared thermal imager for mobile phones, compatible with both Android and iOS devices, achieving wireless image transmission up to 30m. It features a 256×192 thermal imaging resolUT-ion, which can be increased to 512×384 through 4x AI real-time super-resolUT-ion. A 7mm adjustable focus lens ensures clear images at both near and far distances. AI Xiao Rui voice interaction allows for quick parameter settings. Suitable for scenarios such as circuit board inspection, electrical maintenance, equipment inspection, and HVAC leak detection.",
    specs: {
      "Item No.": "UT-IX2 Pro",
      "Payment": "EXW/FOB/CIF/DDU/DAP.",
      "Product origin": "China",
      "Color": "black",
      "Shipping port": "QingDao",
      "Lead Time": "7",
      "Min order": "10"
    },
    inStock: true,
  },
  {
    id: 3,
    name: "China Best Of Thermal Imaging Camera UT-460TC",
    model: "UT-460TC",
    category: "thermal-camera",
    subCategory: "Thermal Imaging Camera",
    price: "Contact Us",
    priceNum: 0,
    badge: "New",
    badgeColor: "bg-green-500",
    rating: 4.8,
    reviews: 130,
    image: "/images/products/ut-460tc/main.jpg",
    images: [
      "/images/products/ut-460tc/main.jpg",
      "/images/products/ut-460tc/detail1.jpg",
      "/images/products/ut-460tc/detail2.jpg",
      "/images/products/ut-460tc/detail3.jpg",
      "/images/products/ut-460tc/detail4.jpg",
      "/images/products/ut-460tc/detail5.jpg",
      "/images/products/ut-460tc/detail6.jpg",
      "/images/products/ut-460tc/detail7.jpg",
      "/images/products/ut-460tc/detail8.jpg",
      "/images/products/ut-460tc/detail9.jpg",
      "/images/products/ut-460tc/detail10.jpg"
    ],
    description: "UT-460TC is a high-performance, high-precision network-based thermal imager that uses an uncooled infrared focal plane array detector. Multiple lenses are available, providing clear and accurate infrared images and temperature measurement capabilities. UT-460TC supports various communication protocols including Modbus TCP, ONVIF, and GB28181, and comes with professional infrared temperature analysis software and SDK. Its small size and low power consumption facilitate system integration in machine vision, power, rail transportation, and industrial aUT-omation applications.",
    specs: {
      "Item No.": "UT-460TC",
      "Payment": "EXW/FOB/CIF/DDU/DAP.",
      "Product origin": "China",
      "Color": "black",
      "Shipping port": "QingDao",
      "Lead Time": "15"
    },
    inStock: true,
  },
  {
    id: 4,
    name: "TROY 3D View Of Electric Microscope Model: UT-2K30/4K30-EP3D_B",
    model: "UT-2K30/4K30-EP3D_B",
    category: "3d-microscope",
    subCategory: "3D Digital Microscope",
    price: "Contact Us",
    priceNum: 0,
    badge: "New",
    badgeColor: "bg-green-500",
    rating: 4.8,
    reviews: 140,
    image: "/images/products/ut-2k30/main.jpg",
    images: [
      "/images/products/ut-2k30/main.jpg",
      "/images/products/ut-2k30/detail1.jpg",
      "/images/products/ut-2k30/detail2.jpg",
      "/images/products/ut-2k30/detail3.jpg",
      "/images/products/ut-2k30/detail4.jpg",
      "/images/products/ut-2k30/detail5.jpg",
      "/images/products/ut-2k30/detail6.jpg",
      "/images/products/ut-2k30/detail7.jpg",
      "/images/products/ut-2k30/detail8.jpg"
    ],
    description: "The UT-2K30/4K30 high-definition industrial camera is easy to use, featuring a built-in personalized interface editing function, template application, mouse operation, USB flash drive storage, and includes functions such as aUT-omatic edge finding, aUT-omatic contouring, horizontal and vertical flipping, line/circle calibration, data export, and playback browsing. It also provides various measurement tools such as \"parallel lines,\" \"point-to-line,\" \"concentric circles,\" angles, and radians.",
    specs: {
      "Item No.": "UT-2K30/4K30-EP3D_B",
      "Payment": "CIF, EXW, FOB, DDU, DAP",
      "Product origin": "China",
      "Color": "purple",
      "Shipping port": "QingDao",
      "Lead Time": "15",
      "Min order": "20"
    },
    inStock: true,
  },
  {
    id: 5,
    name: "China Top Of Pcb Microscope UT-9218/9118",
    model: "UT-9218/9118",
    category: "electronic-microscope",
    subCategory: "PCB Microscope",
    price: "Contact Us",
    priceNum: 0,
    badge: "New",
    badgeColor: "bg-green-500",
    rating: 4.8,
    reviews: 150,
    image: "/images/products/ut-9218/main.jpg",
    images: [
      "/images/products/ut-9218/main.jpg",
      "/images/products/ut-9218/detail1.jpg",
      "/images/products/ut-9218/detail2.jpg",
      "/images/products/ut-9218/detail3.jpg",
      "/images/products/ut-9218/detail4.jpg",
      "/images/products/ut-9218/detail5.jpg",
      "/images/products/ut-9218/detail6.jpg",
      "/images/products/ut-9218/detail7.jpg",
      "/images/products/ut-9218/detail8.jpg",
      "/images/products/ut-9218/detail9.jpg",
      "/images/products/ut-9218/detail10.jpg",
      "/images/products/ut-9218/detail11.jpg",
      "/images/products/ut-9218/detail12.jpg"
    ],
    description: "ResolUT-ion: 1920 x 1080 Frame Rate: 60fps Optical Size: 1/3 inch Network Interface: None Video Interface: HDMI IO Interface: None USB Interface: 1 Storage Method: SD Card Storage",
    specs: {
      "Item No.": "UT-9218/9118",
      "Payment": "CIF, EXW, FOB, DDU, DAP",
      "Product origin": "China",
      "Color": "black",
      "Shipping port": "QingDao",
      "Lead Time": "15",
      "Min order": "20"
    },
    inStock: true,
  },
  {
    id: 6,
    name: "One-BUT-ton MINI AOI Machine UT-A100",
    model: "UT-A100",
    category: "vision-inspection",
    subCategory: "AOI Machine",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 160,
    image: "/images/products/ut-a100/main.jpg",
    images: [
      "/images/products/ut-a100/main.jpg",
      "/images/products/ut-a100/detail1.jpg",
      "/images/products/ut-a100/detail2.jpg",
      "/images/products/ut-a100/detail3.jpg",
      "/images/products/ut-a100/detail4.jpg",
      "/images/products/ut-a100/detail5.jpg",
      "/images/products/ut-a100/detail6.jpg",
      "/images/products/ut-a100/detail7.jpg",
      "/images/products/ut-a100/detail8.jpg",
      "/images/products/ut-a100/detail9.jpg",
      "/images/products/ut-a100/detail10.jpg",
      "/images/products/ut-a100/detail11.jpg",
      "/images/products/ut-a100/detail12.jpg",
      "/images/products/ut-a100/detail13.jpg",
      "/images/products/ut-a100/detail14.jpg",
      "/images/products/ut-a100/detail15.jpg",
      "/images/products/ut-a100/detail16.jpg",
      "/images/products/ut-a100/detail17.jpg"
    ],
    description: "ncluding machinery, electronics, mold making, injection molding, metals, rubber, low-voltage electrical appliances, magnetic materials, precision stamping, connectors, terminals, mobile phones, home appliances, printed circuit boards, medical devices, and watches etc.",
    specs: {
      "Item No.": "UT-A100",
      "Payment": "CIF, EXW, FOB, DDU, DAP",
      "Product origin": "China",
      "Color": "white",
      "Shipping port": "QingDao",
      "Lead Time": "15"
    },
    inStock: true,
  },
  {
    id: 7,
    name: "World Top Of Depth Of Field Microscope UT-600II",
    model: "UT-600II",
    category: "electronic-microscope",
    subCategory: "Depth Of Field Microscope",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 170,
    image: "/images/products/ut-600ii/main.jpg",
    images: [
      "/images/products/ut-600ii/main.jpg",
      "/images/products/ut-600ii/detail1.jpg",
      "/images/products/ut-600ii/detail2.jpg",
      "/images/products/ut-600ii/detail3.jpg",
      "/images/products/ut-600ii/detail4.jpg",
      "/images/products/ut-600ii/detail5.jpg",
      "/images/products/ut-600ii/detail6.jpg",
      "/images/products/ut-600ii/detail7.jpg",
      "/images/products/ut-600ii/detail8.jpg",
      "/images/products/ut-600ii/detail9.jpg",
      "/images/products/ut-600ii/detail10.jpg",
      "/images/products/ut-600ii/detail11.jpg",
      "/images/products/ut-600ii/detail12.jpg"
    ],
    description: "Function 1: Flashlight; Solve the problem of unclear fonts on PCBA chips Function 2: Depth of field synthesis; Solve the problem of blurred display of different depths of field Function 3: Light source shielding; Solve the problem of reflection of FPC soft board affecting observation Function 4: Ethernet port; It is convenient to transfer pictures, and there is no problem with rejecting USB disk.",
    specs: {
      "Item No.": "UT-600II_A",
      "Payment": "EXW, FOB, CIF",
      "Product origin": "China",
      "Color": "White and Blue",
      "Shipping port": "QingDao",
      "Lead Time": "7-14"
    },
    inStock: true,
  },
  {
    id: 8,
    name: "Utcom  3D View Type Of Electric Microscope Model: UT-8008_A",
    model: "UT-8008_A",
    category: "3d-microscope",
    subCategory: "3D Digital Microscope",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 180,
    image: "/images/products/ut-8008-a/main.jpg",
    images: [
      "/images/products/ut-8008-a/main.jpg",
      "/images/products/ut-8008-a/detail1.jpg",
      "/images/products/ut-8008-a/detail2.jpg",
      "/images/products/ut-8008-a/detail3.jpg",
      "/images/products/ut-8008-a/detail4.jpg",
      "/images/products/ut-8008-a/detail5.jpg",
      "/images/products/ut-8008-a/detail6.jpg",
      "/images/products/ut-8008-a/detail7.jpg",
      "/images/products/ut-8008-a/detail8.jpg",
      "/images/products/ut-8008-a/detail9.jpg",
      "/images/products/ut-8008-a/detail10.jpg"
    ],
    description: "Model number：UT-8008_A Series：Multi-function ResolUT-ion：1920*1080 Video Port：HDMI Color：Colour Sensor Size：1/3\" USB Port：2 Port Storage mode：U-disk Storage Lens interface：C-Mount Power：DC 12V",
    specs: {
      "Item No.": "UT-8008_A",
      "Payment": "CIF, EXW, FOB, DDU, DAP",
      "Product origin": "China",
      "Color": "White",
      "Shipping port": "QingDao",
      "Lead Time": "15",
      "Min order": "10"
    },
    inStock: true,
  },
  {
    id: 9,
    name: "China Top Of AI Image Measuring Instrument",
    model: "UT-AI300CNC",
    category: "measuring-microscope",
    subCategory: "AI Measuring Instrument",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 190,
    image: "/images/products/ut-ai300cnc/main.jpg",
    images: [
      "/images/products/ut-ai300cnc/main.jpg",
      "/images/products/ut-ai300cnc/detail1.jpg",
      "/images/products/ut-ai300cnc/detail2.jpg",
      "/images/products/ut-ai300cnc/detail3.jpg",
      "/images/products/ut-ai300cnc/detail4.jpg",
      "/images/products/ut-ai300cnc/detail5.jpg",
      "/images/products/ut-ai300cnc/detail6.jpg"
    ],
    description: "Provide efficient and complete measurement solUT-ions for high-end customers, suitable for domestic military industry, aerospace, aUT-omobile engines, scientific research institUT-es, semiconductors, chips, precision electronics and other high-end manufacturing industries. Exclusively develop AI-guided intelligent capture and edge grabbing algorithms to achieve aUT-omatic recognition and measurement of all surface feature boundaries.",
    specs: {
      "Item No.": "UT-AI300CNC",
      "Payment": "CIF, EXW, FOB, UDP",
      "Product origin": "China",
      "Color": "Grey",
      "Shipping port": "QingDao",
      "Lead Time": "20"
    },
    inStock: true,
  },
  {
    id: 10,
    name: "China Top Of SEM Microscope UT3200",
    model: "UT-3200",
    category: "specialized-microscope",
    subCategory: "SEM Microscope",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 200,
    image: "/images/products/ut3200/main.jpg",
    images: [
      "/images/products/ut3200/main.jpg",
      "/images/products/ut3200/detail1.jpg",
      "/images/products/ut3200/detail2.jpg",
      "/images/products/ut3200/detail3.jpg",
      "/images/products/ut3200/detail4.jpg",
      "/images/products/ut3200/detail5.jpg",
      "/images/products/ut3200/detail6.jpg",
      "/images/products/ut3200/detail7.jpg",
      "/images/products/ut3200/detail8.jpg"
    ],
    description: "High-performance tungsten SEM microscope with excellent image quality capabilities in both high and low vacuum modes.  With a large depth of field and a user-friendly interface, the TR3200 SEM microscope enables users to characterize samples and explore the world of microscopic imaging and analysis.",
    specs: {
      "Item No.": "UT3200",
      "Payment": "CIF, EXW, FOB, UDP",
      "Product origin": "China",
      "Color": "White",
      "Shipping port": "QingDao",
      "Lead Time": "45"
    },
    inStock: true,
  },
  {
    id: 11,
    name: "China Top Of Smart Vision Camera UT-SmartGo",
    model: "UT-SmartGo",
    category: "vision-inspection",
    subCategory: "Smart Vision Camera",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 210,
    image: "/images/products/ut-smartgo/main.jpg",
    images: [
      "/images/products/ut-smartgo/main.jpg",
      "/images/products/ut-smartgo/detail1.jpg",
      "/images/products/ut-smartgo/detail2.jpg",
      "/images/products/ut-smartgo/detail3.jpg",
      "/images/products/ut-smartgo/detail4.jpg",
      "/images/products/ut-smartgo/detail5.jpg",
      "/images/products/ut-smartgo/detail6.jpg",
      "/images/products/ut-smartgo/detail7.jpg",
      "/images/products/ut-smartgo/detail8.jpg",
      "/images/products/ut-smartgo/detail9.jpg",
      "/images/products/ut-smartgo/detail10.jpg",
      "/images/products/ut-smartgo/detail11.jpg",
      "/images/products/ut-smartgo/detail12.jpg",
      "/images/products/ut-smartgo/detail13.jpg",
      "/images/products/ut-smartgo/detail14.jpg",
      "/images/products/ut-smartgo/detail15.jpg",
      "/images/products/ut-smartgo/detail16.jpg",
      "/images/products/ut-smartgo/detail17.jpg"
    ],
    description: "Model: UT-SmartGo Type: Smart Vision Inspection Camera ResolUT-ion: 1600 x 1400 Frame rate: Color/Black and White Network interface: 100Mbps Video interface: HDMI IO interface: IO interface, RS232, power interface USB interface: 2 Storage method: U disk storage",
    specs: {
      "Item No.": "UT-SmartGo_CL/BW",
      "Payment": "CIF, EXW, FOB, UDP",
      "Product origin": "China",
      "Color": "Grey",
      "Shipping port": "QingDao",
      "Lead Time": "7"
    },
    inStock: true,
  },
  {
    id: 12,
    name: "Utcom Brand Of Deep View Electronic Microscope",
    model: "UT-S6000NMX",
    category: "electronic-microscope",
    subCategory: "Deep View Electronic Microscope",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 220,
    image: "/images/products/ut-s6000nmx/main.jpg",
    images: [
      "/images/products/ut-s6000nmx/main.jpg",
      "/images/products/ut-s6000nmx/detail1.jpg",
      "/images/products/ut-s6000nmx/detail2.jpg",
      "/images/products/ut-s6000nmx/detail3.jpg",
      "/images/products/ut-s6000nmx/detail4.jpg",
      "/images/products/ut-s6000nmx/detail5.jpg",
      "/images/products/ut-s6000nmx/detail6.jpg",
      "/images/products/ut-s6000nmx/detail7.jpg",
      "/images/products/ut-s6000nmx/detail8.jpg"
    ],
    description: "Model: UT-S6000NMX Type: Electron microscope ResolUT-ion: 1920 X 1080 Frame rate: 60fps. Optical size: 1/1.2\" Network interface: 100MB/s.",
    specs: {
      "Item No.": "UT-S6000NMX",
      "Payment": "CIF, EXW, FOB, UDP",
      "Product origin": "China",
      "Color": "Pink",
      "Shipping port": "QingDao",
      "Lead Time": "15"
    },
    inStock: true,
  },
  {
    id: 13,
    name: "China Top Of Digital Metallographic Microscope UT-MT4K80",
    model: "UT-MT4K80",
    category: "metallographic-microscope",
    subCategory: "Digital Metallographic Microscope",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 230,
    image: "/images/products/ut-mt4k80/main.jpg",
    images: [
      "/images/products/ut-mt4k80/main.jpg",
      "/images/products/ut-mt4k80/detail1.jpg",
      "/images/products/ut-mt4k80/detail2.jpg",
      "/images/products/ut-mt4k80/detail3.jpg",
      "/images/products/ut-mt4k80/detail4.jpg",
      "/images/products/ut-mt4k80/detail5.jpg",
      "/images/products/ut-mt4k80/detail6.jpg",
      "/images/products/ut-mt4k80/detail7.jpg",
      "/images/products/ut-mt4k80/detail8.jpg",
      "/images/products/ut-mt4k80/detail9.jpg",
      "/images/products/ut-mt4k80/detail10.jpg",
      "/images/products/ut-mt4k80/detail11.jpg",
      "/images/products/ut-mt4k80/detail12.jpg"
    ],
    description: "Digital metallographic microscope(UT-MT4K80) is an optical inspection equipment developed for high-end manufacturing and research in the semiconductor industry, silicon wafer manufacturing industry, electronic information industry, metallurgical industry, medical testing, scientific research, etc.As a high-end metallographic microscope, users can experience its excellent image effects and a clear microscopic world at high magnification when using it. The MT40 microscope can be widely used in semiconductor research and development, manufacturing, FPD, circuit packaging, circuit substrates, materials, castings/metal/ceramic parts, and precision mold inspection.This instrument uses a high-power LED lighting lamp with two lighting forms: reflection and transmission. Bright and dark field ob...",
    specs: {
      "Item No.": "UT-MT4K80",
      "Payment": "EXW, FOB, CIF",
      "Product origin": "China",
      "Color": "White",
      "Shipping port": "QingDao",
      "Lead Time": "14"
    },
    inStock: true,
  },
  {
    id: 14,
    name: "China Best Of Digital Metallographic Microscope UT-MT60_B",
    model: "UT-MT60_B",
    category: "metallographic-microscope",
    subCategory: "Digital Metallographic Microscope",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 240,
    image: "/images/products/ut-mt60-b/main.jpg",
    images: [
      "/images/products/ut-mt60-b/main.jpg",
      "/images/products/ut-mt60-b/detail1.jpg",
      "/images/products/ut-mt60-b/detail2.jpg",
      "/images/products/ut-mt60-b/detail3.jpg",
      "/images/products/ut-mt60-b/detail4.jpg",
      "/images/products/ut-mt60-b/detail5.jpg",
      "/images/products/ut-mt60-b/detail6.jpg",
      "/images/products/ut-mt60-b/detail7.jpg",
      "/images/products/ut-mt60-b/detail8.jpg",
      "/images/products/ut-mt60-b/detail9.jpg",
      "/images/products/ut-mt60-b/detail10.jpg",
      "/images/products/ut-mt60-b/detail11.jpg",
      "/images/products/ut-mt60-b/detail12.jpg",
      "/images/products/ut-mt60-b/detail13.jpg",
      "/images/products/ut-mt60-b/detail14.jpg",
      "/images/products/ut-mt60-b/detail15.jpg",
      "/images/products/ut-mt60-b/detail16.jpg"
    ],
    description: "Electron Metallographic Digital Microscope UT-MT60_B of main features:The atmosphere is stable and the operation is more flexible. It integrates various observation functions such as bright field, dark field, polarized light, and DIC differential interference, which can be selected according to actual applications.",
    specs: {
      "Item No.": "UT-MT60_B",
      "Payment": "EXW, FOB, CIF",
      "Product origin": "China",
      "Color": "White",
      "Shipping port": "QingDao",
      "Lead Time": "15"
    },
    inStock: true,
  },
  {
    id: 15,
    name: "China Top Of 3d Digital Microscope UT-360A",
    model: "UT-360A",
    category: "3d-microscope",
    subCategory: "3D Digital Microscope",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 250,
    image: "/images/products/ut-360a/main.jpg",
    images: [
      "/images/products/ut-360a/main.jpg",
      "/images/products/ut-360a/detail1.jpg",
      "/images/products/ut-360a/detail2.jpg",
      "/images/products/ut-360a/detail3.jpg",
      "/images/products/ut-360a/detail4.jpg",
      "/images/products/ut-360a/detail5.jpg",
      "/images/products/ut-360a/detail6.jpg",
      "/images/products/ut-360a/detail7.jpg",
      "/images/products/ut-360a/detail8.jpg",
      "/images/products/ut-360a/detail9.jpg",
      "/images/products/ut-360a/detail10.jpg"
    ],
    description: "*Three-dimensional viewing plane 3D mode can be switched *Light source continuous reading adjustable 0.7-4.5X optical magnification adjustable *Image storage Frame freeze, image comparison*Strong light suppression, edge enhancement *Color Independent Adjustment *White balance adjustment, AUT-omatically adjust exposure *High speed 60 frames per second, Mouse operation, U disk read and write",
    specs: {
      "Item No.": "UT-360A",
      "Payment": "EXW, FOB, CIF",
      "Product origin": "China",
      "Color": "Silver",
      "Shipping port": "QingDao",
      "Lead Time": "10"
    },
    inStock: true,
  },
  {
    id: 16,
    name: "China Top Of All In One Microscope UT-600II",
    model: "UT-600II_A",
    category: "electronic-microscope",
    subCategory: "All In One Microscope",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 260,
    image: "/images/products/ut-600ii-pii/main.jpg",
    images: [
      "/images/products/ut-600ii-pii/main.jpg",
      "/images/products/ut-600ii-pii/detail1.jpg",
      "/images/products/ut-600ii-pii/detail2.jpg",
      "/images/products/ut-600ii-pii/detail3.jpg",
      "/images/products/ut-600ii-pii/detail4.jpg",
      "/images/products/ut-600ii-pii/detail5.jpg",
      "/images/products/ut-600ii-pii/detail6.jpg",
      "/images/products/ut-600ii-pii/detail7.jpg",
      "/images/products/ut-600ii-pii/detail8.jpg",
      "/images/products/ut-600ii-pii/detail9.jpg",
      "/images/products/ut-600ii-pii/detail10.jpg",
      "/images/products/ut-600ii-pii/detail11.jpg",
      "/images/products/ut-600ii-pii/detail12.jpg",
      "/images/products/ut-600ii-pii/detail13.jpg"
    ],
    description: "(1) Magnification knob: Rotate the magnification knob to make the image the right size on the display, depending on the size of the product (2) Light source: Ring light source (3) Up and down adjustment knob: adjusts to the height of the product to give a clear image (4) Light source adjustment knob: adjusts the level of brightness of the light source (5) USB port: can be connected to a USB mouse for operation and a U disk for saving pictures",
    specs: {
      "Item No.": "UT-600II_PII",
      "Payment": "EXW, FOB, CIF",
      "Product origin": "China",
      "Color": "White and Blue",
      "Shipping port": "QingDao",
      "Lead Time": "7"
    },
    inStock: true,
  },
  {
    id: 17,
    name: "China Top 3D Depth Digital Microscope UT-3D9000",
    model: "UT-3D9000",
    category: "3d-microscope",
    subCategory: "3D Depth Digital Microscope",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 270,
    image: "/images/products/ut-3d9000/main.jpg",
    images: [
      "/images/products/ut-3d9000/main.jpg",
      "/images/products/ut-3d9000/detail1.jpg",
      "/images/products/ut-3d9000/detail2.jpg",
      "/images/products/ut-3d9000/detail3.jpg",
      "/images/products/ut-3d9000/detail4.jpg",
      "/images/products/ut-3d9000/detail5.jpg",
      "/images/products/ut-3d9000/detail6.jpg",
      "/images/products/ut-3d9000/detail7.jpg",
      "/images/products/ut-3d9000/detail8.jpg",
      "/images/products/ut-3d9000/detail9.jpg",
      "/images/products/ut-3d9000/detail10.jpg",
      "/images/products/ut-3d9000/detail11.jpg",
      "/images/products/ut-3d9000/detail12.jpg",
      "/images/products/ut-3d9000/detail13.jpg"
    ],
    description: "*High-quality optical system *HD lens *Multiple objective selection *Stereoscopic 3d imaging *High-precision measurement *Quality assurance",
    specs: {
      "Item No.": "UT-3D9000",
      "Payment": "EXW, FOB, CIF",
      "Product origin": "China",
      "Color": "Black",
      "Shipping port": "QingDao",
      "Lead Time": "20"
    },
    inStock: true,
  },
  {
    id: 18,
    name: "China Best Of 3D Digital Microscope UT-800+P3D",
    model: "UT-800+P3D",
    category: "3d-microscope",
    subCategory: "3D Digital Microscope",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 280,
    image: "/images/products/ut-800-p3d/main.jpg",
    images: [
      "/images/products/ut-800-p3d/main.jpg",
      "/images/products/ut-800-p3d/detail1.jpg",
      "/images/products/ut-800-p3d/detail2.jpg",
    ],
    description: "The entire body (including the lens, LED light, and processing unit); 13 inch Screen; Accessories (DC power calbe for Microscope/screen, mouse, HDMI cable)",
    specs: {
      "Item No.": "UT-800_P3D",
      "Payment": "EXW, FOB, CIF",
      "Product origin": "China",
      "Color": "White",
      "Shipping port": "QingDao",
      "Lead Time": "14",
      "Min order": "10"
    },
    inStock: true,
  },
  {
    id: 19,
    name: "China Best Of AUT-ofocus Digital Microscope UT-3500AF",
    model: "UT-3500AF",
    category: "electronic-microscope",
    subCategory: "Autofocus Digital Microscope",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 290,
    image: "/images/products/ut-3500af/main.jpg",
    images: [
      "/images/products/ut-3500af/main.jpg",
      "/images/products/ut-3500af/detail1.jpg",
      "/images/products/ut-3500af/detail2.jpg",
    ],
    description: "*Built-in precision optical focusing system -all in one *Software fast algorithm *AUT-o-focus in real-time, within the adjustable range, no need to adjust *AUT-o-focus precise picture rendering",
    specs: {
      "Item No.": "UT-3500AF",
      "Payment": "EXW, FOB, CIF",
      "Product origin": "China",
      "Color": "Red",
      "Shipping port": "QingDao",
      "Lead Time": "10"
    },
    inStock: true,
  },
  {
    id: 20,
    name: "Top Of Microscope Electron UT-MS8001",
    model: "UT-MS8001",
    category: "specialized-microscope",
    subCategory: "Microscope Electron",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 300,
    image: "/images/products/ut-ms8001/main.jpg",
    images: [
      "/images/products/ut-ms8001/main.jpg",
      "/images/products/ut-ms8001/detail1.jpg",
      "/images/products/ut-ms8001/detail2.jpg",
    ],
    description: "Such as microscope for PCB board inspection and QC department. Also University Class etc.",
    specs: {
      "Item No.": "UT-MS8001",
      "Payment": "EXW, FOB, CIF",
      "Product origin": "China",
      "Color": "White",
      "Shipping port": "QingDao",
      "Lead Time": "7"
    },
    inStock: true,
  },
  {
    id: 21,
    name: "Hot Sale Of Manual 3d Microscope UT-800_3D",
    model: "UT-800_3D",
    category: "3d-microscope",
    subCategory: "Manual 3D Microscope",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 310,
    image: "/images/products/ut-800-3d/main.jpg",
    images: [
      "/images/products/ut-800-3d/main.jpg",
      "/images/products/ut-800-3d/detail1.jpg",
      "/images/products/ut-800-3d/detail2.jpg",
    ],
    description: "*LED ring light source, dynamic adjustment *AUT-omatic edge finding *AUT-omatic circle finding *Picture save and export *Data save and export *Zoom withoUT- blur",
    specs: {
      "Item No.": "UT-800_3D",
      "Payment": "FOB/CIF",
      "Product origin": "China",
      "Color": "White",
      "Shipping port": "QingDao",
      "Lead Time": "7"
    },
    inStock: true,
  },
  {
    id: 22,
    name: "China Industrial Robot Vision Camera Supplier",
    model: "UT-Smart-2000M",
    category: "vision-inspection",
    subCategory: "Robot Vision Camera",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 320,
    image: "/images/products/ut-smart-2000m/main.jpg",
    images: [
      "/images/products/ut-smart-2000m/main.jpg",
      "/images/products/ut-smart-2000m/detail1.jpg",
    ],
    description: "* Industrial Robots vision system * Industrial machines vision system * Defect Products Inspection * Porduct Position Controls * QC Checking for micro products",
    specs: {
      "Item No.": "Smart-2000M",
      "Payment": "FOB/CIF",
      "Product origin": "China",
      "Color": "Black",
      "Shipping port": "QingDao",
      "Lead Time": "15",
      "Min order": "5"
    },
    inStock: true,
  },
  {
    id: 23,
    name: "China Best Industrial Electronic Microscope With Monitor For PCB Board Inspection J",
    model: "UT-600",
    category: "electronic-microscope",
    subCategory: "Industrial Electronic Microscope",
    price: "Contact Us",
    priceNum: 0,
    rating: 4.8,
    reviews: 330,
    image: "/images/products/ut-600/main.jpg",
    images: [
      "/images/products/ut-600/main.jpg",
      "/images/products/ut-600/detail1.jpg",
      "/images/products/ut-600/detail2.jpg",
    ],
    description: "*Graphic overlay *Microscope *HDMI camera *Video microscope",
    specs: {
      "Item No.": "UT-600",
      "Payment": "FOB / CIF",
      "Market price": "$2000",
      "Product origin": "China",
      "Color": "White",
      "Shipping port": "QingDao",
      "Lead Time": "7"
    },
    inStock: true,
  },
];
